<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '* Resize table columns just like a spreadsheet by dragging the column edges.' => '',
    'Ok' => '',
    'Show first page data' => '',
    'Class Name' => '@@Nombre de Clase@@',
    'Data' => '@@@@',
    'Description' => '@@Descripción@@',
    'ID' => '@@@@',
    'Name' => '@@Nombre@@',
    'Permission name' => '@@Nombre del permiso@@',
    'Permissions' => '@@Permisos@@',
    'Role name' => '@@Nombre del rol@@',
    'Roles' => '@@Roles@@',
    'Rule Name' => '@@Nombre de regla@@',
    'Rule not exists' => '@@La regla no existe@@',
    'User ID' => '@@ID de usuario@@',
    '(not use)' => '(sin uso)',
    'All' => 'Todo',
    'Are you sure want to delete this item' => '¿está seguro(a) que desea borrar este ítem?',
    'Are you sure?' => '¿está seguro(a)?',
    'Assignment' => 'Asignación',
    'Cancel' => 'Cancelar',
    'Close' => 'Cerrar',
    'Create More' => 'Crear Más',
    'Create new rule' => 'Crear Nueva Regla',
    'Create new {0}' => 'Crear {0}',
    'Delete' => 'Borrar',
    'Edit' => 'Editar',
    'Have been create new {0} success' => 'Nuevo {0} creado satisfactoriamente',
    'Page' => 'Página',
    'Permissions Manager' => 'Gestor de Permisos',
    'Reload Grid' => 'Recargar Grilla',
    'Roles Manager' => 'Gestor de Roles',
    'Rules Manager' => 'Gestor de Reglas',
    'Save' => 'Guardar',
    'Show all data' => 'Mostrar todos los datos',
    'The requested page does not exist.' => 'La página solicitada no existe.',
    'Update' => 'Actualizar',
    'Update {0}' => 'Actualizar {0}',
    'User Assignment' => 'Asignación de Usuario',
    'View' => 'Ver',
];
