<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add/Edit/Delete Checkout for Library Members.' => '',
    'Checkout Privileges' => '',
    'Settings changed successfuly.' => 'Configuraciones actualizadas satisfactoriamente.',
    'Add/Edit/Delete Bibliograhical Collections.' => 'Agregar/Editar/Borrar Colecciones Bibliográficas.',
    'Add/Edit/Delete Classification for Library Members.' => 'Agregar/Editar/Borrar Clasificaciones para Miembros de la Biblioteca.',
    'Add/Edit/Delete Material types for Library.' => 'Agregar/Editar/Borrar Tipos de material para la Biblioteca',
    'Add/Edit/Delete Themes.' => 'Agregar/Editar/Borrar Temas.',
    'Basic Library Settings.' => 'Configuración básica de la Biblioteca',
    'Collections' => 'Colecciones',
    'Library Settings' => 'Configuración de la Biblioteca',
    'Material Types' => 'Tipos de Material',
    'Member Classify' => 'Clasificación de Miembros',
    'Themes' => 'Temas',
];
