<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Copy' => 'Agregar Copia',
    'Bibid' => '',
    'Biblio' => '',
    'Call Nmbr2' => '',
    'Call Nmbr3' => '',
    'Circulation' => 'Circulación',
    'Code' => 'Código',
    'Collection' => 'Colección',
    'Collection Cd' => '',
    'Create User' => 'Registrar usuario',
    'Daily Late Fee' => 'Cargo diario por mora',
    'Days Due Back' => 'Días atrasados',
    'Default Flg' => '',
    'Field Data' => '',
    'Fieldid' => '',
    'ID' => '',
    'Ind1 Cd' => '',
    'Ind2 Cd' => '',
    'Mbr ID' => '',
    'No' => '',
    'Renewal Count' => '',
    'Repeatable Flg' => '',
    'Search User' => 'Buscar usuario',
    'Status' => 'Estado',
    'Status Begin Dt' => '',
    'Subfield Cd' => '',
    'Updated Userid' => '',
    'Users' => 'Usuarios',
    'Additional Bibliographic Information' => 'Información bibliográfica adicional',
    'Are you sure you want to delete this item?' => '¿Está seguro que desea borrar este ítem?',
    'Author' => 'Autor',
    'Barcode Nmbr' => 'Código de copia',
    'Biblio Copies' => 'Copias Bibliográficas',
    'Biblio Search' => 'Búsqueda Bibliográfica',
    'Bibliography Copy Information' => 'Información de la copia bibliográfica',
    'Biblios' => 'Catalogación',
    'Call Nmbr1' => 'Número de entrada',
    'Collections' => 'Colecciones',
    'Copy Desc' => 'Descripción de la Copia',
    'Create' => 'Crear',
    'Create Biblio' => 'Nuevo Material Bibliográfico',
    'Create Biblio Copy' => 'Crear Copia Bibliográfica',
    'Create Collection' => 'Crear Colección',
    'Create Material Type' => 'Crear tipo de material',
    'Created At' => 'Creado el',
    'Delete' => 'Borrar',
    'Description' => 'Descripción',
    'Due Back Dt' => 'Fecha de devolución',
    'Home' => 'Inicio',
    'Image File' => 'Archivo de imagen',
    'Login' => 'Iniciar sesión',
    'Logout' => 'Cerrar Sesión',
    'Material Cd' => 'Tipo de Material',
    'Material Types' => 'Tipos de Material',
    'New Member' => 'Nuevo Usuario',
    'Check in' => 'Recepción',
    'Opac Flg' => 'Mostrar en Opac',
    'Reset' => 'Restablecer',
    'Responsibility Stmt' => 'Mención de responsabilidad, etc.',
    'Search' => 'Buscar',
    'Status Cd' => 'Estado',
    'Tag' => 'Etiqueta',
    'Title' => 'Título',
    'Title Remainder' => 'Resto del título',
    'Topic1' => 'Termino temático o nombre geográfico como elemento de entrada',
    'Topic2' => 'Termino temático o nombre geográfico como elemento de entrada',
    'Topic3' => 'Termino temático o nombre geográfico como elemento de entrada',
    'Topic4' => 'Termino temático o nombre geográfico como elemento de entrada',
    'Topic5' => 'Termino temático o nombre geográfico como elemento de entrada',
    'USMarc Fields:' => 'Campos USMarc',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}',
    'Updated At' => 'Actualizado el',
    'User' => 'Usuario',
    'Yes' => 'Sí',
    'You are not allowed to perform this action.' => 'No está autorizado para realizar esta acción.',
];
