<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Bibid' => '',
    'Biblio' => '',
    'Call Nmbr1' => '',
    'Call Nmbr2' => '',
    'Call Nmbr3' => '',
    'Collection Cd' => '',
    'Collections' => '',
    'Dayli Late Fee' => '',
    'Days Due Back' => '',
    'Default Flg' => '',
    'Field Data' => '',
    'Fieldid' => '',
    'ID' => '',
    'Ind1 Cd' => '',
    'Ind2 Cd' => '',
    'No' => '',
    'Repeatable Flg' => '',
    'Responsibility Stmt' => '',
    'Subfield Cd' => '',
    'Title Remainder' => 'Resto del título',
    'Topic1' => 'Termino temático o nombre geográfico como elemento de entrada',
    'Topic2' => 'Termino temático o nombre geográfico como elemento de entrada',
    'Topic3' => 'Termino temático o nombre geográfico como elemento de entrada',
    'Topic4' => 'Termino temático o nombre geográfico como elemento de entrada',
    'Topic5' => 'Termino temático o nombre geográfico como elemento de entrada',
    'Updated Userid' => '',
    'Yes' => 'Sí',
    'Are you sure you want to delete this item?' => '¿Está seguro que desea borrar este ítem?',
    'Author' => 'Autor',
    'Biblio Search' => 'Búsqueda Bibliográfica',
    'Biblios' => 'Catalogación',
    'Create' => 'Crear',
    'Create Biblio' => 'Nuevo Material Bibliográfico',
    'Create Collection' => 'Crear Colección',
    'Create Material Type' => 'Crear tipo de material',
    'Created At' => 'Creado el',
    'Delete' => 'Borrar',
    'Description' => 'Descripción',
    'Home' => 'Inicio',
    'Image File' => 'Archivo de imagen',
    'Login' => 'Iniciar sesión',
    'Logout' => 'Cerrar Sesión',
    'Material Cd' => 'Tipo de Material',
    'Material Types' => 'Tipos de Material',
    'Opac Flg' => 'Mostrar en Opac',
    'Reset' => 'Restablecer',
    'Search' => 'Buscar',
    'Tag' => 'Etiqueta',
    'Title' => 'Título',
    'USMarc Fields:' => 'Campos USMarc',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}',
    'Updated At' => 'Actualizado el',
    'User' => 'Usuario',
    'You are not allowed to perform this action.' => 'No está autorizado para realizar esta acción.',
];
