<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Author' => 'Autor',
    'Bibid' => '',
    'Biblio' => '',
    'Biblio Search' => 'Búsqueda Bibliográfica',
    'Biblios' => 'Material Bibliográfico',
    'Call Nmbr1' => '',
    'Call Nmbr2' => '',
    'Call Nmbr3' => '',
    'Collection Cd' => '',
    'Create' => 'Crear',
    'Create Biblio' => 'Nuevo Material Bibliográfico',
    'Created At' => '',
    'Delete' => 'Borrar',
    'Field Data' => '',
    'Home' => 'Inicio',
    'ID' => '',
    'Ind1 Cd' => '',
    'Ind2 Cd' => '',
    'Material Cd' => '',
    'Opac Flg' => '',
    'Reset' => 'Restablecer',
    'Responsibility Stmt' => '',
    'Search' => 'Buscar',
    'Subfield Cd' => '',
    'Tag' => '',
    'Title' => 'Título',
    'Title Remainder' => '',
    'Topic1' => '',
    'Topic2' => '',
    'Topic3' => '',
    'Topic4' => '',
    'Topic5' => '',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'Updated Userid' => '',
];
