<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Item {n, number} has reached its renewal limit.' => '',
    'Item {n, number} is late and cannot be renewed.' => '',
    'Item {n, number} is on hold to another member.' => '',
    'Late fee (barcode={n, number})' => '',
    'Member has reached checkout limit for this collection.' => '',
    'Note: Member has an outstanding account balance of {t, total}.' => '',
    'This member is currently blocked.' => '',
    'holdMessageMsg1' => '',
    'Item placed hold.' => 'Ítem reservado.',
    'Item {n, number} is already checked out to another member.' => 'El ítem {n, number} ya fue tomado por otro miembro.',
    'This item is not checked out or on hold.' => 'Este ítem no se encuentra prestado o reservado.',
    'This member already has that item checked out -- not placing hold.' => 'Este miembro ya tiene en préstamo este ítem -- no se reserva.',
    'This member already has that item placed hold -- not placing hold.' => 'Este miembro ya tiene en reserva este ítem -- no se reserva.',
];
