<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Note: Member has an outstanding account balance of {total}.' => '@@Nota: El miembro tiene un saldo de cuenta pendiente de {total}@@',
    'Item placed hold.' => 'Ítem reservado.',
    'Item {n, number} has reached its renewal limit.' => 'El elemento {n, número} ha alcanzado su límite de renovación.',
    'Item {n, number} is already checked out to another member.' => 'El ítem {n, number} ya fue tomado por otro miembro.',
    'Item {n, number} is late and cannot be renewed.' => 'El artículo {n, number} llega tarde y no se puede renovar.',
    'Item {n, number} is on hold to another member.' => 'El artículo {n, número} está reservado por otro miembro.',
    'Late fee (barcode={n, number})' => 'Cargo por demora (barcode={n, number})',
    'Member has reached checkout limit for this collection.' => 'El miembro ha alcanzado el límite de préstamos para esta colección.',
    'Note: Member has an outstanding account balance of {0, number, currency}.' => 'Nota: El miembro tiene un saldo de cuenta pendiente de {0, number, currency}.',
    'The bibliography with barcode number {barcode} that you are attempting to check in has one or more hold requests placed on it.  <b>Please file this bibliography with your held items instead of placing it on your shelving cart.</b>  The status code for this bibliography has been set to hold.' => 'La bibliografía con el número de código de barras {barcode} que está intentando registrar tiene una o más solicitudes de bloqueo. <b> Archive esta bibliografía con los elementos que tenga en su lugar en lugar de colocarlos en su carrito de estanterías. </ b> El código de estado de esta bibliografía se ha configurado para que se mantenga.',
    'This item is not checked out or on hold.' => 'Este ítem no se encuentra prestado o reservado.',
    'This member already has that item checked out -- not placing hold.' => 'Este miembro ya tiene en préstamo este ítem -- no se reserva.',
    'This member already has that item placed hold -- not placing hold.' => 'Este miembro ya tiene en reserva este ítem -- no se reserva.',
    'This member is currently blocked.' => 'Este miembro está actualmente bloqueado.',
];
