#!/bin/bash

/var/lib/openshift/$OPENSHIFT_APP_UUID/app-root/runtime/bin/php -v
export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"

if [ ! -f "$OPENSHIFT_DATA_DIR/composer.phar" ]; then
    curl -s https://getcomposer.org/installer | php -- --install-dir=$OPENSHIFT_DATA_DIR
else
    /var/lib/openshift/$OPENSHIFT_APP_UUID/app-root/runtime/bin/php $OPENSHIFT_DATA_DIR/composer.phar self-update
fi

( unset GIT_DIR ; cd $OPENSHIFT_REPO_DIR ; /var/lib/openshift/$OPENSHIFT_APP_UUID/app-root/runtime/bin/php $OPENSHIFT_DATA_DIR/composer.phar install ) 