# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#image: phpunit/phpunit:5.0.3
image: python:3.5.1

pipelines:
  default:
    - step:
        caches:
            - pip
            - boto3
        script: # Modify the commands below to build your repository.
          - apt-get update # required to install zip
          - apt-get install -y zip # required for packaging up the application
          - pip install boto3==1.3.0
          - zip -r obib2.zip .ebextensions backend build common console environments frontend vagrant codeception.yml .bowerrc composer.json composer.lock init Vagrantfile yii -x beanstalk_deploy.py bitbucket-pipelines.yml
          - python beanstalk_deploy.py # run the deployment script 
