<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Callno' => '',
    'Checkout Count' => '',
    'Create' => '',
    'Create Acquisitions' => '',
    'Generated' => '',
    'ID' => '',
    'Over Due Member List' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Acquisition' => 'Adquisición',
    'Cataloging' => 'Catalogación',
    'Circulation' => 'Préstamos',
    'Statistics' => 'Estadísticas',
    'Acquisitions' => 'Adquisiciones',
    'Bibliography Copy' => 'Copia Bibliográfica',
    'Biblography' => 'Bibliografía',
    'Choose from one of the following links to run a report.' => 'Elija de uno de los siguientes enlaces para iniciar un reporte',
    'Copy Search' => 'Buscar Copia',
    'Group By' => 'Agrupar por',
    'Most Popular Bibliographies' => 'Bibliografías más populares',
    'Num Of  Copies' => 'Num de Copias',
    'Reports' => 'Reportes',
    'Results' => 'Resultados',
];
