insert into {{%collection_dm}} values (1,'Adult Fiction','N',21,0.05);
insert into {{%collection_dm}} values (2,'Adult Nonfiction','Y',21,0.05);
insert into {{%collection_dm}} values (3,'Cassettes','N',7,0.05);
insert into {{%collection_dm}} values (4,'Compact Discs','N',7,0.15);
insert into {{%collection_dm}} values (5,'Computer Software','N',7,0.15);
insert into {{%collection_dm}} values (6,'Easy Readers','N',21,0.05);
insert into {{%collection_dm}} values (7,'Juvenile Fiction','N',21,0.05);
insert into {{%collection_dm}} values (8,'Juvenile Nonfiction','N',21,0.05);
insert into {{%collection_dm}} values (9,'New Books','N',14,0.10);
insert into {{%collection_dm}} values (10,'Periodics','N',14,0.05);
insert into {{%collection_dm}} values (11,'Reference','N',0,0.00);
insert into {{%collection_dm}} values (12,'Videos and DVDs','N',3,1.00);
insert into {{%collection_dm}} values (13,'Digital Books','N',3,1.00);