<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Acquisitions' => '',
    'Author' => '',
    'Barcode Nmbr' => '',
    'Bibid' => '',
    'Bibliography Checkout Listing' => '',
    'Bibliography Copy' => '',
    'Biblography' => '',
    'Call Num' => '',
    'Callno' => '',
    'Checkout' => '',
    'Checkout Count' => '',
    'Choose from one of the following links to run a report.' => '',
    'Copy Search' => '',
    'Create' => '',
    'Create Acquisitions' => '',
    'Cycle' => '',
    'Due' => '',
    'Due Back Dt' => '',
    'Group By' => '',
    'ID' => '',
    'Item Checkout History' => '',
    'Mbr ID' => '',
    'Month' => '',
    'Most Popular Bibliographies' => '',
    'Name' => '',
    'Num Of  Copies' => '',
    'Over Due Member List' => '',
    'Periodic Checkout Count' => '',
    'Pin' => '',
    'Reports' => '',
    'Results' => '',
    'Status Begin Dt' => '',
    'Time Span' => '',
    'Title' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Week' => '',
    'Are you sure you want to delete this item?' => '@@@@',
    'Delete' => '@@@@',
    'Export to PDF' => '@@@@',
    'Generated' => '@@@@',
];
