insert into {{%collection_dm}} values (1,'Ficción para adultos','N',21,0.05);
insert into {{%collection_dm}} values (2,'No ficción para adultos','Y',21,0.05);
insert into {{%collection_dm}} values (3,'Casetes','N',7,0.05);
insert into {{%collection_dm}} values (4,'Discos compactos','N',7,0.15);
insert into {{%collection_dm}} values (5,'Software de Computadora','N',7,0.15);
insert into {{%collection_dm}} values (6,'Lectura Fácil','N',21,0.05);
insert into {{%collection_dm}} values (7,'Ficción juvenil','N',21,0.05);
insert into {{%collection_dm}} values (8,'No ficción juvenil','N',21,0.05);
insert into {{%collection_dm}} values (9,'Nuevos libros','N',14,0.10);
insert into {{%collection_dm}} values (10,'Periódicos','N',14,0.05);
insert into {{%collection_dm}} values (11,'Referencia','N',0,0.00);
insert into {{%collection_dm}} values (12,'Videos y DVDs','N',3,1.00);
insert into {{%collection_dm}} values (13,'Libros Digitales','N',3,1.00);