<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Additional Bibliographic Information' => '',
    'Are you sure you want to delete this item?' => '',
    'Author' => '',
    'Barcode Nmbr' => '',
    'Bibid' => '',
    'Biblio' => '',
    'Biblio Copies' => '',
    'Biblio Search' => '',
    'Bibliography Copy Information' => '',
    'Biblios' => '',
    'Call Nmbr1' => '',
    'Call Nmbr2' => '',
    'Call Nmbr3' => '',
    'Collection' => '',
    'Collection Cd' => '',
    'Collections' => '',
    'Copy Desc' => '',
    'Create' => '',
    'Create Biblio' => '',
    'Create Biblio Copy' => '',
    'Create Collection' => '',
    'Create Material Type' => '',
    'Created At' => '',
    'Dayli Late Fee' => '',
    'Days Due Back' => '',
    'Default Flg' => '',
    'Delete' => '',
    'Description' => '',
    'Due Back Dt' => '',
    'Field Data' => '',
    'Fieldid' => '',
    'Home' => '',
    'ID' => '',
    'Image File' => '',
    'Ind1 Cd' => '',
    'Ind2 Cd' => '',
    'Login' => '',
    'Logout' => '',
    'Material Cd' => '',
    'Material Types' => '',
    'Mbr ID' => '',
    'No' => '',
    'Opac Flg' => '',
    'Renewal Count' => '',
    'Repeatable Flg' => '',
    'Reset' => '',
    'Search' => '',
    'Status Begin Dt' => '',
    'Status Cd' => '',
    'Subfield Cd' => '',
    'Tag' => '',
    'Title' => '',
    'Title Remainder' => '',
    'Topic1' => '',
    'Topic2' => '',
    'Topic3' => '',
    'Topic4' => '',
    'Topic5' => '',
    'USMarc Fields:' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'Updated Userid' => '',
    'User' => '',
    'Yes' => '',
    'You are not allowed to perform this action.' => '',
    'Status Begint Dt' => '@@@@',
    'user' => '@@@@',
    'Responsibility Stmt' => 'Statement of responsibility, etc.',
];
