<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account' => '',
    'Amount' => '',
    'Are you absolutely sure? You will lose all the information about this user with this action.' => '',
    'Are you sure you want to delete this item?' => '',
    'Charge' => '',
    'Checked in {barcode}' => '',
    'Create Member Account' => '',
    'Credit' => '',
    'Delete' => '',
    'Details' => '',
    'Has reserved' => '',
    'Item placed hold.' => '',
    'Item {n, number} has reached its renewal limit.' => '',
    'Item {n, number} is already checked out to another member.' => '',
    'Item {n, number} is late and cannot be renewed.' => '',
    'Item {n, number} is on hold to another member.' => '',
    'Late fee (barcode={n, number})' => '',
    'Member Accounts' => '',
    'Member has reached checkout limit for this collection.' => '',
    'Member updated successfully' => '',
    'No new holds' => '',
    'Note: Member has an outstanding account balance of {0, number, currency}' => '',
    'Payment' => '',
    'Print QR' => '',
    'Profile' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'The bibliography with barcode number {barcode} that you are attempting to check in has one or more hold requests placed on it.  <b>Please file this bibliography with your held items instead of placing it on your shelving cart.</b>  The status code for this bibliography has been set to hold.' => '',
    'The requested page does not exist.' => '',
    'This item is already checked out or on hold.' => '',
    'This item is not checked out or on hold.' => '',
    'This member already has that item checked out -- not checking out.' => '',
    'This member already has that item checked out -- not placing hold.' => '',
    'This member already has that item placed hold -- not checking out.' => '',
    'This member already has that item placed hold -- not placing hold.' => '',
    'This member is currently blocked.' => '',
    'Transaction Type Cd' => '',
    'Update' => '',
    'Update Member Account: {nameAttribute}' => '',
    'Note: Member has an outstanding account balance of ${0, number, #,#.0#}' => '@@@@',
    'Note: Member has an outstanding account balance of {0, number}' => '@@@@',
    'Note: Member has an outstanding account balance of {total}.' => '@@@@',
    'Pay' => '@@@@',
];
