<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Payment' => '',
    'Update Member Account: {nameAttribute}' => 'Actualizar Cuenta de Miembro: {nameAttribute}',
    'The item {barcode} is already on cart' => '@@El artículo {barcode} ya está en el carrito.@@',
    'This item is already checked out or on hold.' => '@@Este artículo ya se encuentra en préstamo o reserva.@@',
    'Account' => 'Cuenta',
    'Amount' => 'Monto',
    'Are you absolutely sure? You will lose all the information about this user with this action.' => '¿Está completamente seguro/a? Perderá toda la información sobre este usuario con esta acción.',
    'Before proceed, please be sure your address is correct. {address}<br /> Is your address correct?' => 'Antes de proceder, asegúrese que su dirección sea correcta. {address}<br /> ¿es esta su dirección?',
    'Charge' => 'Cargo',
    'Checked in {barcode}' => '{barcode} revisado',
    'Create Member Account' => 'Crear Cuenta de Miembro',
    'Credit' => 'Crédito',
    'Details' => 'Detalles',
    'Item added to cart.' => 'Artículo añadido al carro.',
    'Item placed hold.' => 'Ítem reservado.',
    'Item {barcode} checked out.' => 'Artículo {barcode} revisado.',
    'Item {n, number} has reached its renewal limit.' => 'El elemento {n, número} ha alcanzado su límite de renovación.',
    'Item {n, number} is already checked out to another member.' => 'El ítem {n, number} ya fue tomado por otro miembro.',
    'Item {n, number} is late and cannot be renewed.' => 'El artículo {n, number} llega tarde y no se puede renovar.',
    'Item {n, number} is on hold to another member.' => 'El artículo {n, número} está reservado por otro miembro.',
    'Late fee (barcode={n, number})' => 'Cargo por demora (barcode={n, number})',
    'Member Accounts' => 'Cuentas de Miembro',
    'Member has reached checkout limit for this collection.' => 'El miembro ha alcanzado el límite de préstamos para esta colección.',
    'Member updated successfully' => 'Miembro actualizado satisfactoriamente',
    'No new holds' => 'Sin nuevas reservas',
    'Note: Member has an outstanding account balance of {0, number, currency}' => 'Nota: El miembro tiene un saldo de cuenta pendiente de {0, number, currency}',
    'Place holds' => 'Reservas',
    'Print List' => 'Imprimir Lista',
    'Print QR' => 'Imprimir QR',
    'Profile' => 'Perfil',
    'The bibliography with barcode number {barcode} that you are attempting to check in has one or more hold requests placed on it.  <b>Please file this bibliography with your held items instead of placing it on your shelving cart.</b>  The status code for this bibliography has been set to hold.' => 'La bibliografía con número de código de barras {barcode} que estás intentando conseguir tiene una o más peticiones de reserva. <strong>Por favor, retorna el item en las estanterías</strong>. El código de estado para esta bibliografía se ha establecido en "reservado".',
    'The item is already on cart' => 'El artículo ya se encuentra en el carrito.',
    'The requested page does not exist.' => 'La página solicitada no existe.',
    'This item is not checked out or on hold.' => 'Este ítem no se encuentra prestado o reservado.',
    'This member already has that item checked out -- not placing hold.' => 'Este miembro ya tiene en préstamo este ítem -- no se reserva.',
    'This member already has that item placed hold -- not placing hold.' => 'Este miembro ya tiene en reserva este ítem -- no se reserva.',
    'This member is currently blocked.' => 'Este miembro está actualmente bloqueado.',
    'Transaction Type Cd' => 'Tipo de Transacción',
    'placed hold copy' => 'reservó la copia',
];
