<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Call Nmbr2' => '',
    'Call Nmbr3' => '',
    'Bibid' => '@@@@',
    'Copyid' => '@@@@',
    'Author' => 'Autor',
    'Barcode Nmbr' => 'Código de copia',
    'Biblio Copies' => 'Copias Bibliográficas',
    'Call Nmbr1' => 'Número de entrada',
    'Copy Desc' => 'Descripción de la Copia',
    'Topic1' => 'Termino temático o nombre geográfico como elemento de entrada',
    'Topic2' => 'Termino temático o nombre geográfico como elemento de entrada',
    'Topic3' => 'Termino temático o nombre geográfico como elemento de entrada',
    'Topic4' => 'Termino temático o nombre geográfico como elemento de entrada',
    'Topic5' => 'Termino temático o nombre geográfico como elemento de entrada',
    'USMarc Fields:' => 'Campos USMarc',
];
