<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Bibid' => '',
    'Call Num' => '',
    'Callno' => '',
    'Checkout' => '',
    'Due' => '',
    'ID' => '',
    'Mbr ID' => '',
    'Periodic Checkout Count' => 'Recuento periódico de préstamos',
    'Pin' => '',
    'Time Span' => 'Espacio de tiempo',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Acquisition' => 'Adquisición',
    'Cataloging' => 'Catalogación',
    'Circulation' => 'Préstamos',
    'Statistics' => 'Estadísticas',
    'Status Begin Dt' => 'Fecha de comienzo de estado',
    'Acquisitions' => 'Adquisiciones',
    'Author' => 'Autor',
    'Barcode Nmbr' => 'Código de copia',
    'Bibliography Checkout Listing' => 'Listado de bibliografía prestada',
    'Bibliography Copy' => 'Copia Bibliográfica',
    'Biblography' => 'Bibliografía',
    'Checkout Count' => 'Conteo de préstamo',
    'Choose from one of the following links to run a report.' => 'Elija de uno de los siguientes enlaces para iniciar un reporte',
    'Copy Search' => 'Buscar Copia',
    'Cycle' => 'Ciclo',
    'Group By' => 'Agrupar por',
    'Item Checkout History' => 'Historial de artículos pedidos',
    'Month' => 'Mes',
    'Most Popular Bibliographies' => 'Bibliografías más populares',
    'Num Of  Copies' => 'Num de Copias',
    'Over Due Member List' => 'Lista de socios con artículos pendientes de devolución',
    'Quarter' => 'Cuarto',
    'Reports' => 'Reportes',
    'Results' => 'Resultados',
    'Title' => 'Título',
    'Week' => 'Semana',
];
