<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add/Edit/Delete Bibliograhical Collections.' => '',
    'Add/Edit/Delete Checkout for Library Members.' => '',
    'Add/Edit/Delete Classification for Library Members.' => '',
    'Add/Edit/Delete Material types for Library.' => '',
    'Add/Edit/Delete Themes.' => '',
    'Basic Library Settings.' => '',
    'Checkout Privileges' => '',
    'Collections' => '',
    'Library Settings' => '',
    'Material Types' => '',
    'Member Classify' => '',
    'Settings changed successfuly.' => '',
    'Themes' => '',
];
